#!/bin/bash

# 🎵 VibeJam-2 Sound Download Script
# Lädt alle benötigten Fantasy-Sounds für das Projekt herunter

echo "🎵 VibeJam-2 Fantasy Sound Downloader"
echo "====================================="
echo ""

# Erstelle Verzeichnisse
mkdir -p assets/sounds/actions
mkdir -p assets/sounds/ambient

echo "📋 Benötigte Sounds für VibeJam-2:"
echo "=================================="
echo ""

echo "🌊 Ambient Sounds (30+ Sekunden, loopbar):"
echo "  - fireplace.mp3 (Kamin-Knistern)"
echo "  - cauldron-bubble.mp3 (Kessel-Bubbeln)"
echo ""

echo "🎯 Action Sounds (1-3 Sekunden):"
echo "  - spell-cast.mp3 (Zauber wirken)"
echo "  - room-change.mp3 (Raum wechseln)"
echo "  - object-click.mp3 (Objekt anklicken)"
echo "  - magic-success.mp3 (Magie erfolgreich)"
echo "  - magic-fail.mp3 (Magie fehlgeschlagen)"
echo "  - gesture-recognized.mp3 (Geste erkannt)"
echo ""

echo "🔮 Object-Specific Sounds (Interaktive Objekte):"
echo "  - fireplace-ignite.mp3 (Kamin anzünden)"
echo "  - lamp-on.mp3 (Lampe einschalten)"
echo "  - chest-open.mp3 (Truhe öffnen)"
echo "  - crystal-ball.mp3 (Kristallkugel aktivieren)"
echo "  - book-open.mp3 (Buch öffnen)"
echo ""

echo "🏆 Additional Sounds:"
echo "  - room-unlock.mp3 (Raum freischalten)"
echo "  - quest-complete.mp3 (Quest abgeschlossen)"
echo "  - achievement-unlock.mp3 (Achievement freigeschaltet)"
echo ""

echo "🎯 Empfohlene Download-Quellen:"
echo "=============================="
echo ""

echo "1. 🥇 Freesound.org (Beste Auswahl):"
echo "   URL: https://freesound.org"
echo "   Registrierung: Kostenlos erforderlich"
echo "   Suchbegriffe:"
echo "     - 'fireplace crackling'"
echo "     - 'magical sparkle'"
echo "     - 'spell cast'"
echo "     - 'portal whoosh'"
echo "     - 'chest open'"
echo "     - 'book page turn'"
echo "     - 'crystal chime'"
echo "     - 'cauldron bubble'"
echo "     - 'lamp click'"
echo "     - 'magic success'"
echo "     - 'magic fail'"
echo ""

echo "2. 🥈 OpenGameArt.org (Keine Registrierung):"
echo "   URL: https://opengameart.org/content/fantasy-sound-effects-library"
echo "   Direkter Download möglich"
echo ""

echo "3. 🥉 Pixabay (Kostenlos):"
echo "   URL: https://pixabay.com/sound-effects/search/fantasy/"
echo "   Keine Registrierung erforderlich"
echo ""

echo "📥 Download-Befehle (Beispiele):"
echo "================================"
echo ""

echo "# Beispiel für curl-Downloads (URLs müssen ersetzt werden):"
echo ""
echo "# Ambient Sounds:"
echo "curl -L -o assets/sounds/ambient/fireplace.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/ambient/cauldron-bubble.mp3 'URL_HIER'"
echo ""
echo "# Action Sounds:"
echo "curl -L -o assets/sounds/actions/spell-cast.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/room-change.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/object-click.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/magic-success.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/magic-fail.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/gesture-recognized.mp3 'URL_HIER'"
echo ""
echo "# Object Sounds:"
echo "curl -L -o assets/sounds/actions/fireplace-ignite.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/lamp-on.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/chest-open.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/crystal-ball.mp3 'URL_HIER'"
echo "curl -L -o assets/sounds/actions/book-open.mp3 'URL_HIER'"
echo ""

echo "🎯 Schnellstart-Anleitung:"
echo "========================"
echo ""
echo "1. Gehen Sie zu: https://freesound.org"
echo "2. Registrieren Sie sich kostenlos"
echo "3. Suchen Sie nach den oben genannten Begriffen"
echo "4. Filtern Sie nach 'Creative Commons'"
echo "5. Laden Sie MP3-Dateien herunter"
echo "6. Benennen Sie sie entsprechend um"
echo "7. Legen Sie sie in die richtigen Verzeichnisse"
echo ""

echo "📁 Verzeichnisstruktur:"
echo "======================"
echo ""
echo "assets/sounds/"
echo "├── ambient/"
echo "│   ├── fireplace.mp3"
echo "│   └── cauldron-bubble.mp3"
echo "└── actions/"
echo "    ├── spell-cast.mp3"
echo "    ├── room-change.mp3"
echo "    ├── object-click.mp3"
echo "    ├── magic-success.mp3"
echo "    ├── magic-fail.mp3"
echo "    ├── gesture-recognized.mp3"
echo "    ├── fireplace-ignite.mp3"
echo "    ├── lamp-on.mp3"
echo "    ├── chest-open.mp3"
echo "    ├── crystal-ball.mp3"
echo "    └── book-open.mp3"
echo ""

echo "🔍 Sound-Qualitäts-Checkliste:"
echo "==============================="
echo ""
echo "✅ Format: MP3"
echo "✅ Qualität: 44.1kHz, 16-bit"
echo "✅ Größe: < 1MB pro Datei"
echo "✅ Ambient: 30+ Sekunden, loopbar"
echo "✅ Actions: 1-3 Sekunden"
echo "✅ Lizenz: Creative Commons oder Public Domain"
echo ""

echo "🎵 Test-Script:"
echo "==============="
echo ""
echo "# Nach dem Download können Sie die Sounds testen:"
echo "python3 -c \"import pygame; pygame.mixer.init(); pygame.mixer.music.load('assets/sounds/ambient/fireplace.mp3'); pygame.mixer.music.play()\""
echo ""

echo "✅ Script beendet!"
echo "   Verwenden Sie die obigen Anleitungen, um alle benötigten Sounds herunterzuladen."
